In [6]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression

In [7]:
ads = pd.read_csv("https://raw.githubusercontent.com/hovhannisyan91/aca/refs/heads/main/lab/python/data/regression/advertising_and_sales.csv")
ads.head()

        tv     radio  social_media influencer      sales
0  16000.0   6566.23       2907.98       Mega   54732.76
1  13000.0   9237.76       2409.57       Mega   46677.90
2  41000.0  15886.45       2913.41       Mega  150177.83
3  83000.0  30020.03       6922.30       Mega  298246.34
4  15000.0   8437.41       1406.00      Micro   56594.18

In [8]:
channel_results = []

for channel in ["tv", "radio", "social_media"]:
    X_channel = ads[[channel]]
    y_sales = ads["sales"]

    channel_model = LinearRegression()
    channel_model.fit(X_channel, y_sales)

    y_hat = channel_model.predict(X_channel)

    r2_channel = 1 - np.sum((y_sales - y_hat) ** 2) / np.sum((y_sales - y_sales.mean()) ** 2)
    rmse_channel = np.sqrt(np.mean((y_sales - y_hat) ** 2))

    channel_results.append({
        "channel": channel,
        "intercept": channel_model.intercept_,
        "slope": channel_model.coef_[0],
        "r_squared": r2_channel,
        "rmse": rmse_channel
    })

pd.DataFrame(channel_results).round(4)

        channel    intercept    slope  r_squared        rmse
0            tv    -132.4925   3.5615     0.9990   2948.5897
1         radio   40586.8007   8.3616     0.7545  46081.4060
2  social_media  118672.5717  22.1879     0.2782  79019.9030